name: B-ondXperience
favicon: null
layout_spectrum: 0.50299
typography_spectrum: 0.34531
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5
  lightness: 0.15795078850351274
  saturation: 1
  rhythmicContrast: 0.7340616527944803
purpose: []
