name: B-ondXperience
favicon: null
layout_spectrum: 0
typography_spectrum: 0.34531
title: Beyond Experience
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-82055907-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
